### ISSUE TITLE
State management, persistence and resumption

### ISSUE THREAD

**Issue by Boostrix** [Significant-Gravitas/AutoGPT#4105]
### Objectives 🚀
- [ ] Organize the application state into well-defined components
    * Update: the easiest way to realize this seems to be `autogpt.core` (#4770)
- [ ] Implement a persistence mechanism
- [ ] Implement a rehydration mechanism
- [ ] Allow application state to be exported/transferred
- [ ] Allow resuming a run from any point in the execution history (important for debugging/development)

> **Note**
> This issue has been converted to a roadmap item by a maintainer (@Pwuts). Thanks for creating this overview @Boostrix! <3
> 
> **Original description**
> meta issue to keep track of everything that's been said in the context of suspending/resuming previous [crashed] agpt sessions - ideally with a capability to resume the agent so that it can validate its known workspace artefacts and use not only any data files it has used previously, but especially any custom files, and especially tools/scripts it may have generated - this implies some fort of dependency tracking (e.g. timestamp between folders/files).

### Related
- #430
- #822
- #1176
- #1531
- #3382
- #3542
- #3933
- #4063

Keywords for people searching: saving, resuming, checkpoint, storing, continuing, serializing, pickle

### Motivation 🔦

We need to be able to deal with different forms/types of stateful behavior, for example:

- the actual goal/objective at hand
- LLM interpretation
- local results errors/warnings/success
- side effects (think file system, directories/files)
