### ISSUE TITLE
Auto-GPT Packaging

### ISSUE THREAD

**Issue by collijk** [Significant-Gravitas/AutoGPT#5003]
# Background
Auto-GPT is not a proper python package.  It depends on custom and pretty complicated [installation steps](https://docs.agpt.co/setup/).  

## Related Issues

There are many, many, many issues related to installation and setup.  Here is a sampling:

- #4990 
- #4989
- #4978 
- #4939 
- #4869 
- #4850 
- #4821 
- #4817 
- #4814 
- #4805 
- #4800 
- #4768 
- #4753 
- #4731 
- #4792 
- So many more

## Related PRs

There are fewer open issues, but there have been a few attempts to clean up installation and move us to modern packaging.

- #4970 
- #4849 
- #4833 
- #4668 
- #4646
- #2506 
- #1955 
- #1102 

# The Plan:

- [ ] We need to find out the platform-specific, non-python dependencies for AutoGPT.  We'll need to list these in the install instructions.  I'm running into a host of these on linux for the TTS stuff.  Install instructions will have some `brew`/`apt-get`/whatever windows uses instructions to install those things.
- [ ] Do some code motion.  There are a number of issues with the repo layout right now.
    - [ ] Swap to a  [src layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout) to ensure we're running and testing installed versions of the code.
    - [ ] Clean up a handful of cruft files that are leftover from earlier implementations.
    - [ ] Move settings files out of the repository and into a user directory (as the user may never clone the repo).
- [ ]  Detailed file movement plan:
    - [ ]  /autogpt -> /src/autogpt/
    - [ ]  /data/CURRENT_BULLETIN.md -> {USER_AGPT_DIRECTORY}/CURRENT_BULLETIN.md
    - [ ]  /logs/ -> {USER_AGPT_DIRECTORY}/agents/{AGENT_NAME}/logs
    - [ ]  /plugins/ -> {USER_AGPT_DIRECTORY}/plugins
    - [ ]  /scripts/ -> /src/autogpt/scripts/
    - [ ]  .env.template -> /dev/null 
    - [ ]  .env -> {USER_AGPT_DIRECTORY}/.env 
    - [ ]  ai_settings.yaml -> {USER_AGPT_DIRECTORY}/agents/{AGENT_NAME}/ai_settings.yaml
    - [ ]  azure.yaml.template  -> {USER_AGPT_DIRECTORY}/azure.yaml
    - [ ]  benchmarks.py -> /agbenchmark/benchmarks.py 
    - [ ]  data_ingestion.py -> /dev/null 
    - [ ]  main.py -> /dev/null (never used?)
    - [ ]  plugins_config.yaml -> {USER_AGPT_DIRECTORY}/agents/{AGENT_NAME}/plugins_config.yaml
    - [ ]  prompt_settings.yaml -> {USER_AGPT_DIRECTORY}/prompt_settings.yaml
    - [ ]  run* -> /dev/null
    - [ ]  tests.py -> /dev/null
- [ ] Add a `autogpt setup` command that can make the USER_AGPT_DIRECTORY and fill it with all the necessaries.  
- [ ] Use `poetry` to configure our builds and setup deployment to PyPI (pending some testing from Luke)
- [ ] Integrate `poetry` into CI
- [ ] Update docs

# The Caveats

- This changes the user workflow.  They'll no longer need to clone the repo, but things will no longer be in the places they're used to. That's pretty annoying.
- This changes the developer workflow (though not in any significant way).

# The Benefits 

- We look like a normal python package on PyPI (expanding our audience)
- We can interactively guide the user through setup, instead of making them configure from docs.
- We reduce maintenance overhead by using a standard layout and standard tools.
- Deploying docker images without issues becomes a lot easier/more stable.
- We enable other people to build apps using autogpt as a lib.  
- Users will get the often-requested feature of being able to maintain multiple agents at once.

# The Timeline

Release 0.5.0 (before the end of July).
