### ISSUE TITLE
Auto-GPT developer documentation 📔

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#5191]
Auto-GPT is an experimental project, where we want to encourage involvement and empower anyone to contribute. We also want to work based off of research and data rather than gut feelings. To enable all of this, we need better architectural and design documentation.

## TODO
- [ ] Make Jupyter notebooks for all of our prompting
- [ ] Document the application's program flow (including architectural notes) in Whimsical and/or Markdown
- [ ] Add references to this new documentation in all the right places
    * Contributor guide
    * README
    * Docs site
- [ ] Require PRs to include updates to developer docs if applicable
- [ ] Add documentation delineating all components that can be used (see https://www.home-assistant.io/integrations/)
- [ ] Add documentation on building agents using forge (and other autogpt components)
- [ ] Add library documentation for Forge and AutoGPT components
- [ ] Document supported versions of various components

**Comment by The-Inscrutable-X** [comment]
How would one be able to help with this?

**Comment by ntindle** [comment]
@The-Inscrutable-X a good start would be turning our prompting into reference notebooks so we can iteratively develop

**Comment by nabby27** [comment]
Have you considered using a reward system to incentivize collaboration with external developers? I think people will be more willing to collaborate on this project if there is some kind of financial compensation. I also think that with projects as interesting as this, people want to contribute financially to improve quality and add new features.

I created a platform for this type of situation, [opire.dev](https://opire.dev), and code owners will [receive a % of the rewards](https://docs.opire.dev/rewards/pricing#percentage-for-code-owner) when it is created by someone outside the organization.

AutoGPT is a solid product and I would love to be able to spend money on solving problems and feel like I'm contributing.

**Comment by ReanimationXP** [comment]
How about amending your readme so the first example you give on what to use the tool for doesn't massively, directly contribute to the enshittification of the internet by giving 44,000 people the idea to make automated garbage videos for a quick buck? This project is the internet's environmental equivalent of a trash factory.

**Comment by ReanimationXP** [comment]
I'm sorry you were so hurt by words. My time in IT and on the planet has taught me to be tough skinned and logical, not get caught up in feels if someone criticizes my work, especially when they're right. I doubt you wrote the readme, so I'm not sure why you're offended anyhow.  Enshittification is a massive problem and when I see someone not only contributing to it but suggesting that others do too, I don't see fit to mince words.

**Comment by ntindle** [comment]
I’m not hurt, but do appreciate your concern. I’m pointing out you’re not going to get what you want, and will remain angry about the state of the world unless you fix it yourself.

**Comment by Pwuts** [comment]
Hi @ReanimationXP and welcome to the project. If you don't like the tutorial, please feel free to make a PR to replace it. This is a general purpose platform, and we're in quite an early stage, so the choice of what exactly to demo in the tutorial is less important than demoing the *concept* of the platform, which I think it does just fine for an initial demo. More demos and tutorials will follow later; feel free to contribute to those.

I personally agree that it's not a good idea to build trash factories of any kind. There is too much garbage content out there already. That being said, I think you're overstating the concern. If the final output is trash, how many people will really be tempted to use it for any serious purpose? And if the trash ends up being posted, how many people will actually see it, given that algorithms prioritize engaging content?

Building a trash factory isn't our goal nor is it the point of that video. If the output quality in a demonstrated use case is bad, we'll work on the tutorials and the blocks to improve. Again, feel free to pitch in. That's part of why we're doing this open-source.

P.S. I think you could have conveyed the same message and started a constructive discussion without being so abrasive. That you're right doesn't mean it's productive, justified, or allowable to act like that. Good arguments are much more important than the emotion with which they are conveyed.

**Comment by ReanimationXP** [comment]
![image](https://github.com/user-attachments/assets/933bece0-492c-45f0-a910-d868b87df5dd)
I don't know that I would call a repo with these kind of stats in an "early stage", even if you are from a technical standpoint.

Especially since we're on github, which is already a small percentile of the world, these stats are absolutely massive. Even one person using this tool to produce trash videos is enough to make a dent in something like YouTube, so no I don't believe I am overstating the problem. I'm not suggesting the platform be scrapped, I'm simply suggesting removing such a terribly bad example of what to do with it.  It has an impact.  "Hello World" is a common phrase for a reason - example projects are often copied.

I am not versed with the platform enough to know what qualifies as an appropriate Hello World suggestion that would not have a negative impact on the internet. I would defer to someone else who is.

**Comment by neomorphiz** [comment]
Hello World.
>goodbye
