### ISSUE TITLE
Fix GitHub blocks' output types

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#8166]
* Tweak for #8044
* Part of #8002

## TODO

- [X] Add specific type definitions using `TypedDict` instead of `dict[str, str]` for block outputs
- [X] Output multiple items separately instead of a list of items
- [X] Add ID/number and URL outputs to comment/issue/PR create blocks
