### ISSUE TITLE
Make naming and formatting of blocks and their fields consistent

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#8173]
Our automatic "pretty" formatting of field and block names isn't great. Examples:

* "Read Csv Block"
* "Request Url"
* "Api Key"
* "Rss Url"

These should be set explicitly rather than generated from a class/field name or type name, and imo we also should not be auto-capitalizing every word because aesthetically it just doesn't work.

## TODO

- [ ] Fix naming of block classes (e.g. `ReadCsvBlock` ("Read Csv Block") -> `ReadCSVBlock` ("Read CSV Block")
- [ ] Add `title` parameter to `Block.__init__` which overrides the auto-formatted title, to be used if our prettifying algorithm isn't compatible with the intended block title
- [ ] Set explicit `title` on fields that currently aren't properly formatted (e.g. "Request Url", "Api Key")
