### ISSUE TITLE
Clean up integration credentials storage infra

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#8540]
A few updates were made in the past weeks which have left some technical debt, including:

* [#8283](https://github.com/Significant-Gravitas/AutoGPT/pull/8283)
* [#8403](https://github.com/Significant-Gravitas/AutoGPT/pull/8403)

## TODO

- [X] Docs and maybe a CLI helper for `ENCRYPTION_KEY`. Fernet has very specific requirements for what it accepts as an encryption key.
- [X] Fix `SupabaseIntegrationCredentialsStore` and `IntegrationCredentialsManager` locking mechanisms (see [comment](https://github.com/Significant-Gravitas/AutoGPT/pull/8283/files#r1827924084))
- [X] Rename `SupabaseIntegrationCredentialsStore` to `IntegrationCredentialsStore`
  - [X] Rename `autogpt_libs.supabase_integration_credentials_store` to `integration_credentials_stroe`
- [X] Eliminate all imports from `backend` in `autogpt_libs`. This will probably involve moving `IntegrationCredentialsStore` to `backend`.
