### ISSUE TITLE
UX improvements on `GitHubPullRequestTriggerBlock`

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#8737]
* Part of #8352
* Implement on #8358

## TODO

- [X] Output PR URL from GitHub PR Trigger block
- [X] Improve description of `payload` output
- [X] Clarify difference between `payload` and `pull_request` outputs
- [X] Rename `sender` output to something more intuitive or descriptive
