### ISSUE TITLE
Prevent use of webhook-triggered blocks if `PLATFORM_BASE_URL` is not set

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#8738]
* Part of #8352
* Implement on #8358

## TODO

- [X] Disable webhook-triggered blocks if `PLATFORM_BASE_URL` is not set
- [X] Raise error in `BaseWebhooksManager` on attempt to create webhook if `PLATFORM_BASE_URL` is not set
- [X] Add field validator for `PLATFORM_BASE_URL`
